
/* Drop Tables */

DROP TABLE SOLVED_QUIZ CASCADE CONSTRAINTS;
DROP TABLE QUIZ CASCADE CONSTRAINTS;
DROP TABLE QUIZ_USER CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE QUIZ_NUMBER;
DROP SEQUENCE USER_NUMBER;




/* Create Sequences */

CREATE SEQUENCE QUIZ_NUMBER INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE USER_NUMBER INCREMENT BY 1 START WITH 1;


/* Create Tables */

CREATE TABLE QUIZ
(
   QUIZ_NUMBER number(4,0) NOT NULL,
   QUIZ_NAME varchar2(100) NOT NULL,
   QUIZ_LEVEL varchar2(15) NOT NULL,
   PRIMARY KEY (QUIZ_NUMBER)
);


CREATE TABLE QUIZ_USER
(
   USER_NUMBER number(2,0) NOT NULL,
   USER_ID varchar2(30) NOT NULL UNIQUE,
   USER_PW varchar2(50) NOT NULL,
   USER_NAME varchar2(30) NOT NULL,
   USER_GRADE varchar2(30),
   USER_QUIZCOUNT number(3,0),
   USER_TOTALPOINT number(4,0),   
   PRIMARY KEY (USER_NUMBER)
);


CREATE TABLE SOLVED_QUIZ
(
   USER_NUMBER number(2,0) NOT NULL,
   QUIZ_NUMBER number(4,0) NOT NULL,
   QUIZ_CODE long,
   QUIZ_SYSDATE varchar2(40) NOT NULL,
   CONSTRAINT COMPOSITE_KEY UNIQUE (USER_NUMBER, QUIZ_NUMBER)
);



/* Create Foreign Keys */

ALTER TABLE SOLVED_QUIZ
   ADD FOREIGN KEY (QUIZ_NUMBER)
   REFERENCES QUIZ (QUIZ_NUMBER)
;


ALTER TABLE SOLVED_QUIZ
   ADD FOREIGN KEY (USER_NUMBER)
   REFERENCES QUIZ_USER (USER_NUMBER)
;
